### ISSUE TITLE
"Share page" button does nothing

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/design-library-plugin#119]
Using version 104.v492ed3cce3f2 of design library on Jenkins 2.365 with Chrome 104 on macOS, the "Share page" button does nothing if you click on it.

**Comment by timja** [comment]
I think it only works in Safari

**Comment by timja** [comment]
hmm I think it used to work =/ (not that it was that useful)

**Comment by janfaracik** [comment]
Working now on Safari, some JS got moved around and it broke.
