### ISSUE TITLE
Overhaul ui-samples

### ISSUE THREAD

**Issue by timja** [jenkinsci/design-library-plugin#12]
@janfaracik showed a demo of it at the UX sig today (I'll add a link once available)

@janfaracik can you give me access to your fork or open a draft PR so I can push to it?

**Comment by janfaracik** [comment]
Invited you to the fork 👍

**Comment by timja** [comment]
Thanks for adding, I think you may have some un-pushed changes? Could you push up to your fork with what you have?

**Comment by timja** [comment]
Actually looks fine think I hadn't re-built

**Comment by janfaracik** [comment]
> Actually looks fine think I hadn't re-built

Just pushed again, quite a few changes so would recommend a pull 👍

**Comment by timja** [comment]
I've managed a couple of ways of showing raw text:

for HTML:

```
      <xmp>
		<button class="jenkins-button">Example</button>
      </xmp>
```

for jelly manually escaping the tags and it renders fine:

```
      <xmp>
        &lt;f:submit value="OK"&gt;Example&lt;/f:submit&gt;
      </xmp>
```

![image](https://user-images.githubusercontent.com/21194782/158694296-419c2ad3-4baf-433f-8e03-d10f9f8de45b.png)

**Comment by timja** [comment]
Another alternative would be to load them via JavaScript from `src/main/webapp`

**Comment by timja** [comment]
I pushed an example of loading it via JavaScript I think we'll have the best results with that.

Couldn't find anyway to stop jelly trying to render it otherwise.

**Comment by timja** [comment]
Looks nice now:

![image](https://user-images.githubusercontent.com/21194782/158769630-431133d3-3f0b-461c-b7ae-089f2408d9cf.png)

Code can be cleaned up and prism loaded via npm, or maybe make the Jenkins plugin for it more flexible I couldn't get that one working (didn't try long).

Would be nice for that to be theme-able though

**Comment by timja** [comment]
I pushed some changes @janfaracik to make remote loading trivial.

I'm not sure if we need https://github.com/janfaracik/ui-samples-plugin/blob/overhaul/src/main/resources/jenkins/plugins/ui_samples/preCode.js any more.

It's easier to put the samples in their own file and then IDE support works and then you don't have to worry about pre spacing etc, but can keep it if we need

**Comment by timja** [comment]
What branch should I run this off so it looks the best btw?

**Comment by timja** [comment]
also ping any ideas here on if you have any vision for what this should be doing / features missing

**Comment by janfaracik** [comment]
> What branch should I run this off so it looks the best btw?

This branch https://github.com/janfaracik/jenkins/tree/scalable-icon-support-3-custom-symbols should be best, it includes all the icons from the open PR + rough custom symbol support so all the icons in the overhaul show properly.

**Comment by timja** [comment]
Can you invite me to your jenkins fork too please, minor commit to push to make the tests compile

**Comment by timja** [comment]
I pushed an example of how to re-use actual code and sample code at least for html in the tables sample. That approach won't work for jelly though.

**Comment by timja** [comment]
Worth opening this as a draft PR do you think @janfaracik ?

**Comment by timja** [comment]
I pushed a re-brand commit to update mentions of ui-samples to design library fyi

**Comment by timja** [comment]
I tracked down the CSRF issues, `st:adjunct` needs to be loaded inside of `l:layout`

**Comment by janfaracik** [comment]
> Worth opening this as a draft PR do you think @janfaracik ?

I think so, it's looking really good - cheers :)

**Comment by timja** [comment]
I was wondering if we should have categories? Can always add later though

I was thinking of adding some stuff around:
- how to add custom css / JavaScript 
- Css naming conventions
- Library plugins for JavaScript / CSS

**Comment by timja** [comment]
I created issues for my last comment

I think we can close this now
