### ISSUE TITLE
Is the JavaScript Proxy useful?

### ISSUE THREAD

**Issue by janfaracik** [jenkinsci/design-library-plugin#128]
Whilst it might contain some useful information (?) the Design Library doesn't seem like the right fit for it. I'd suggest we remove it unless it has a genuine use.

**Comment by daniel-beck** [comment]
This shouldn't have replaced `ui-samples` then.

**Comment by timja** [comment]
> This shouldn't have replaced `ui-samples` then.

Not helpful

----

I think this page is useful, it's an area that people often struggle with, and stapler is a framework only used in Jenkins so it's non obvious on how to do this sort of thing.

It could certainly polished and the design library as a whole could probably do with allowing some structure in the side bar to separate things like:

- Components
- Guidance (CSS, JS, whatever)
- Stapler-isms like this
