### ISSUE TITLE
The Hetero List Sample page isn't particularly clear on what it does

### ISSUE THREAD

**Issue by janfaracik** [jenkinsci/design-library-plugin#129]
It would be good to get some better examples/guidance on what it does. However if it isn't useful, much like #128 we could potentially remove it from the Design Library.

**Comment by timja** [comment]
> Given the importance of hetero lists all over the Jenkins UI, what exactly is this plugin for if not for explaining those?

The current example does not do any explaining at all.

----

I think we should either polish / somewhat hide this in a WIP section or remove it.

This section isn't up to scratch with the rest of the content.

**Comment by mawinter69** [comment]
This can be closed
