### ISSUE TITLE
Single quotes incorrectly encoded in French localization

### ISSUE THREAD

**Issue by basil** [jenkinsci/design-library-plugin#164]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22.04.1 LTS x86_64

### Reproduction steps

- Install this plugin as of `origin/HEAD` (at the time of this writing, commit ea8411e).
- Visit e.g. https://127.0.0.1/design-library/AppBar/ in the French locale.

### Expected Results

The first sentence begins with

> Les barres d'applications fournissent l'en-tête de la page

### Actual Results

The first sentence begins with

> Les barres dapplications fournissent len-tête de la page

### Anything else?

The quotes are incorrectly encoded. Per [the Javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/MessageFormat.html):

> A single quote itself must be represented by doubled single quotes `''` throughout a _String_.

**Comment by timja** [comment]
@NotMyFault is this an issue with the crowdin integration?
