### ISSUE TITLE
Improve dark- and whitemode selection on README

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/design-library-plugin#20]
While the selection works fine on GitHub, https://plugins.jenkins.io/design-library/ displays both images side by side:
![](https://i.imgur.com/aN550EZ.png)
![](https://i.imgur.com/iIFtrz6.png)

**Comment by timja** [comment]
Ah I see.

This seems like a plugin-site issue?

https://github.com/jenkins-infra/plugin-site

**Comment by NotMyFault** [comment]
> Ah I see.
> 
> This seems like a plugin-site issue?
> 
> https://github.com/jenkins-infra/plugin-site

The plugin site does currently not use some sort of dark/white mode logic (afaik) and just copies what we provide in the readme.
If the former gets implemented, that is something to take care of then, I guess.

**Comment by timja** [comment]
yes but it's a GitHub feature the plugin site needs to be aware of
