### ISSUE TITLE
Documentation should include from which Jenkins release the content applies

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/design-library-plugin#328]
https://github.com/jenkinsci/matrix-auth-plugin/pull/159 updates the core dependency but it's not immediately clear why.

I know enough to find https://github.com/jenkinsci/design-library-plugin/pull/264 and then https://github.com/jenkinsci/jenkins/commit/1ec59c737a547aeae7c6cd0b38ad2810f02c3891 so that explains it, but documentation should still specify from when it applies so readers don't need to know how the sausage is made to be able to use it.

This isn't unique to the "Dialogs" page: looking through the various pages, none of them specify a required core release.

**Comment by timja** [comment]
It added the capability, and used it on Cards

See e.g. https://weekly.ci.jenkins.io/design-library/cards/

I've got a PR for dialogs here: https://github.com/jenkinsci/design-library-plugin/pull/380
