### ISSUE TITLE
Share link should open dialog at the clicked position

### ISSUE THREAD

**Issue by uhafner** [jenkinsci/design-library-plugin#352]
Share link does not open dialog at the correct position: currently the dialog is shown on the top right of the browser window.

![Image](https://github.com/user-attachments/assets/b3c75878-33c6-4886-94c5-d8569c3d3122)

Tested with Arc Version 1.70.0 (56062) and https://weekly.ci.jenkins.io/design-library/Cards/.

**Comment by timja** [comment]
Works fine in Chrome

**Comment by uhafner** [comment]
Interesting, Arc uses Chromium as rendering engine... On Safari it works as well. On Firefox the icon link is not shown at all, is this intentional?

**Comment by timja** [comment]
Can't remember, share is removed from here anyway:
https://github.com/jenkinsci/design-library-plugin/pull/350

I don't think its useful as at least on mac it just pops something up for sending in a text message and a couple other options, doesn't even copy the link...
