### ISSUE TITLE
Automate Java 21 Installation in gitpod.yml

### ISSUE THREAD

**Issue by SohamJuneja** [jenkinsci/design-library-plugin#367]
### What feature do you want to see added?

Currently, Java 17 needs to be manually installed each time the Gitpod workspace is opened. To streamline the process, the gitpod.yml file should be updated to automate the installation of Java 17.

Suggested Changes:

Add steps in gitpod.yml to automatically install Java 17.
Ensure the correct version of Java is available when the workspace is initialized.

### Are you interested in contributing this feature?

Trying a fix myself, will update with progress soon

**Comment by shinigami-777** [comment]
I think Java 21 installation would make more sense according to [this](https://github.com/jenkinsci/design-library-plugin/blob/master/Jenkinsfile?#L9). Currently gitpod is using Java 11. Can I create a pr for this although @SohamJuneja might be working.

**Comment by SohamJuneja** [comment]
@shinigami-777 Yes, I initially tried using Java 17 but encountered some issues along the way. After further investigation, I realized that Java 21 would be a better fit for the project. I've now created a pull request with Java 21 to address the compatibility issue in Gitpod. Thank you for your input on this!
