### ISSUE TITLE
Boolean button moves on select

### ISSUE THREAD

**Issue by ianwilliams1** [jenkinsci/design-library-plugin#52]
### Jenkins and plugins versions report

<details>
  <summary>
[Design Library](https://weekly.ci.jenkins.io/design-library/)
</summary>

  
N/A

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Any Browser (Chrome | Firefox | Edge | Vivaldi), including mobile

### Reproduction steps

Navigate to: https://weekly.ci.jenkins.io/design-library/Radios/
Choose Boolean Radio and toggle between Yes | No

### Expected Results

Lower radio button remains in situ

### Actual Results

Lower radio button appears to shift vertically by the radius dimension

### Anything else?

_No response

https://user-images.githubusercontent.com/45702008/167596800-f7437edc-4d72-493f-85fc-41706e101bcf.mp4

_

**Comment by mawinter69** [comment]
seems to be fixed.
