### ISSUE TITLE
Validation Form field Tooltip "Delete" hover is slow to disappear

### ISSUE THREAD

**Issue by ianwilliams1** [jenkinsci/design-library-plugin#53]
### Jenkins and plugins versions report

<details>
  <summary>[Design Library](https://weekly.ci.jenkins.io/design-library/)</summary>

  
N/A

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Browser dependent

### Reproduction steps

Navigate to:: https://weekly.ci.jenkins.io/design-library/Validation/
Quickly navigate to a section, observe the "Delete" tooltip
Click on "X" delete a section, then move mouse slightly.
Delete tooltip remains for a period of time AFTEr the delete action has completed.

Behavior has been seen on multiple browsers

### Expected Results

Expect tooltip to disappear at same time as deleted section.
Have not tested to see if this occurs for other tooltips or is specific to validation

### Actual Results

Tooltip remains orphaned for up to 10 seconds AFTER section has been deleted.
In the attached video, delay is ~ 6 secs
Delay is repeatable, but not consistent.

https://user-images.githubusercontent.com/45702008/167593966-fc9d5e3a-d0b7-48ac-ae4f-ea253ed95ad3.mp4

.

**Comment by timja** [comment]
Should be fixed by https://github.com/jenkinsci/jenkins/pull/6408 which is blocked on https://github.com/jenkinsci/matrix-auth-plugin/pull/120

**Comment by mawinter69** [comment]
can be closed
