### ISSUE TITLE
Redirects while using gitpod redirect to localhost rather than url gitpod is running on

### ISSUE THREAD

**Issue by timja** [jenkinsci/design-library-plugin#65]
### Jenkins and plugins versions report

-

### What Operating System are you using (both controller, and any agents involved in the problem)?

-

### Reproduction steps

1. Visit https://gitpod.io/#https://github.com/jenkinsci/design-library-plugin
2. Click 'Design library' when you get to the preview

### Expected Results

Redirected to the design library

### Actual Results

Redirected to http://localhost:8080/jenkins/design-library/

### Anything else?

This case actually shouldn't be redirected, we could fix it by adding a trailing slash so there's no redirect but it's an easy example, there's a number of other cases that cause these redirects to fail.

I did some debugging in https://github.com/jenkinsci/design-library-plugin/pull/63#issuecomment-1126961957
But I haven't tracked down a fix.

The `ReverseProxyAdminMonitor` fails, but the headers look correct =/

**Comment by timja** [comment]
cc @Nancy-Chauhan

**Comment by akosyakov** [comment]
I think it is maybe a bug in Jenkins itself. I checked that workspace proxy already set forwarded headers [[1](https://github.com/gitpod-io/gitpod/blob/aa2c51c80405c1d2da0d58840c27fa7fd0bb746b/components/ws-proxy/pkg/proxy/routes.go#L380-L381)]. But when I run a diagnostic with
```
BASE=administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor
curl -iL -e $(gp url 8080)/jenkins/manage \
            $(gp url 8080)/jenkins/${BASE}/test
```

The redirect URI is following:
```
/jenkins/administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor/testForReverseProxySetup/https:/8080-nancychauha-designlibra-td9pckww72f.ws-eu44xl.gitpod.io/jenkins/manage/
```

**Comment by timja** [comment]
Could be an issue with Jetty.

I think we need to try make the calls directly skipping gitpod and passing headers down to see what's going on.

e.g. 

```
curl -H "Host: 8080-jenkinsci-designlibrary-1qcpytmyc1p.ws-eu45.gitpod.io" -H 'X-Forwarded-Host: 8080-jenkinsci-designlibrary-1qcpytmyc1p.ws-eu45.gitpod.io:443' -H 'X-Forwarded-Proto: https' -v http://localhost:8080/jenkins/design-library
```

But yes as far as I could tell when I spent some time debugging it gitpod was doing it right, unsure why Jenkins is confused.

**Comment by timja** [comment]
Interestingly it works if I use Jenkins itself downloaded from https://www.jenkins.io/download/

May be either config being passed to the jetty plugin or something in maven-hpi-plugin =/.

**Comment by timja** [comment]
(although it still complains thinking the reverse proxy setup is broken everything seems to work)

**Comment by timja** [comment]
Setting host to 0.0.0.0 fixes it
