### ISSUE TITLE
Symbols API do not support href and tooltips

### ISSUE THREAD

**Issue by DuMaM** [jenkinsci/design-library-plugin#74]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.349
OS: Linux - 5.16.20-051620-generic
---
apache-httpcomponents-client-4-api:4.5.13-1.0
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-6
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.4
command-launcher:1.2
credentials:1126.ve05618c41e62
display-url-api:2.3.6
echarts-api:5.3.2-1
font-awesome-api:6.0.0-1
jackson2-api:2.13.2.20220328-281.v9ecc7a_5e834f
javadoc:1.6
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-6
jaxb:2.3.6-1
jdk-tool:1.0
jobConfigHistory:999999-SNAPSHOT (private-fa283965-gitpod)
jquery3-api:3.6.0-3
jsch:0.1.55.2
junit:1.63
mailer:414.vcc4c33714601
matrix-project:771.v574584b_39e60
maven-plugin:3.16
plugin-util-api:2.16.0
popper-api:1.16.1-3
popper2-api:2.11.5-1
scm-api:608.vfa_f971c5a_a_e9
script-security:1158.v7c1b_73a_69a_08
snakeyaml-api:1.30.1
ssh-credentials:277.v95c2fec1c047
sshd:3.0.3
structs:318.va_f3ccb_729b_71
trilead-api:1.57.v6e90e07157e1
workflow-api:1153.vb_912c0e47fb_a_
workflow-step-api:625.vd896b_f445a_f8
workflow-support:819.v37d707a_71d9b_
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Create symbol according to new Symbol API.
Try to add href or tool tip to `l:icon`. 
https://weekly.ci.jenkins.io/design-library/Symbols/

How it's done now you can see in this PR.
https://github.com/jenkinsci/job-config-history-plugin/pull/199#discussion_r882104603

### Expected Results

We should be able to add hrefs and tooltips to symbols.

### Actual Results

We are able to do this, but arguments are ignored.

### Anything else?

The problem source is in this lines.
https://github.com/jenkinsci/jenkins/blob/2d62032ca422c332b8324ff8925444bd4c9562f9/core/src/main/resources/lib/layout/icon.jelly#L66-L76

**Comment by timja** [comment]
Why do you expect to be able to do this?

The tag is about adding an icon.

Any markup you want to add around it can easily be added around it

(and @NotMyFault already suggested that)

**Comment by DuMaM** [comment]
I would rather split icon from symbol if we want to keep it simple.
I got confused after reading documentation about Jelly Icon tag with output i got.
Take look here.
https://reports.jenkins.io/core-taglib/jelly-taglib-ref.html
![image](https://user-images.githubusercontent.com/9051964/170459542-1abe6a6c-bbb0-4c40-9ef4-065e2150badd.png)
Maybe for symbols we should use ionicon?

**Comment by timja** [comment]
symbols used to use ionicon but that is deprecated I think.

the docs don't mention anything about a href? tooltip should work fine though

**Comment by NotMyFault** [comment]
The jelly reference does only build LTS versions, hence the latest symbol/icon src stuff isn't mentioned there.

**Comment by DuMaM** [comment]
I don't know why tooltips wasn't working for me before. Now they are fine.
Probably there was a mistake on mine side.
Same goes for href. I assume i saw some example and i misunderstood it. 
Also If documentation will be updated after LTS, it's fine.
I think we can close this ticket.

Working late sometimes provide strange results 😵‍💫 
Thanks for help and patience.
