### ISSUE TITLE
Remove the 'InpageNavigationWithBreadcrumb' page

### ISSUE THREAD

**Issue by janfaracik** [jenkinsci/design-library-plugin#80]
### Describe your use-case which is not covered by existing documentation.

This page is currently a carry-over from `ui-samples` and hasn't been updated to fit in with the new design. 

https://weekly.ci.jenkins.io/design-library/InpageNavigationWithBreadcrumb/

<img width="190" alt="Screenshot 2022-06-20 at 13 09 10" src="https://user-images.githubusercontent.com/43062514/174598534-0499b969-617a-482f-854c-e6442101d931.png">

The reason why I'd want to remove this page is that interacting with breadcrumbs isn't obvious nor does it provide much functionality. A better approach to navigate through a page would be tabs or sidebar navigation, such as https://github.com/jenkinsci/jenkins/pull/6485.

Would be good to hear thoughts.

**Comment by timja** [comment]
Agreed not a good UX, sounds fine to remove.

(Pointer is also broken for these as well uses the text highlighting one not the same as others)

**Comment by daniel-beck** [comment]
This exists and is both used and supported, so why should we remove documentation for it?

**Comment by janfaracik** [comment]
> Can this be replaced by the regular breadcrumb menu that's used e.g. for the global configuration?

It could be but imo the sidebar we have (or at least will have) is a better approach as it's more discoverable, whereas clicking on a breadcrumb to navigate is quite unusual.
