### ISSUE TITLE
Custom symbols can be themeable

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/design-library-plugin#91]
### Describe your use-case which is not covered by existing documentation.

If custom symbols have a stroke set, they are themable, core replaces the value with `currentColor` to make those symbols reactive to themes.
We should probably outline that on the symbols page, considering people may use custom SVGs which have no property set, leading to unthemable symbols.

**Comment by uhafner** [comment]
Is there a lint for SVG available that checks this?

**Comment by timja** [comment]
> Is there a lint for SVG available that checks this?

It may not be desirable in all cases, i.e. logos.
